"""Architecture smell scanner with rule packs and evidence snippets."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from pattern_intelligence import decision_paths, find_entry


CODE_SUFFIXES = {".cs", ".java", ".ts", ".tsx", ".js", ".jsx", ".py", ".go", ".rs", ".cpp", ".hpp", ".h"}
DOC_SUFFIXES = {".md", ".yml", ".yaml", ".json"}
SKIP_DIRS = {
    ".git",
    ".venv",
    "__pycache__",
    "bin",
    "build",
    "dist",
    "node_modules",
    "obj",
    "site",
    "vendor",
}
GENERATED_PATTERNS = (
    "generated",
    "auto-generated",
    "do not edit",
    "<auto-generated",
)
RULES: list[dict[str, Any]] = [
    {
        "id": "conditional-sprawl",
        "pack": "object-design",
        "severity": "P2",
        "confidence": 0.72,
        "regex": r"\b(if|switch|case|elif)\b",
        "threshold": 12,
        "evidence": "branch-heavy decision logic",
    },
    {
        "id": "provider-switch-sprawl",
        "pack": "object-design",
        "severity": "P2",
        "confidence": 0.78,
        "regex": r"(provider|vendor|driver|implementation|market|customer)",
        "requires": r"\b(if|switch|case|elif)\b",
        "threshold": 3,
        "evidence": "provider or market selection mixed with branching",
    },
    {
        "id": "overused-singleton",
        "pack": "object-design",
        "severity": "P3",
        "confidence": 0.65,
        "regex": r"\b(singleton|static\s+\w+\s+Instance|global\s+)",
        "threshold": 1,
        "evidence": "global instance or singleton language",
    },
    {
        "id": "god-service",
        "pack": "object-design",
        "severity": "P2",
        "confidence": 0.62,
        "regex": r"(class|struct|service|manager|handler)",
        "line_threshold": 500,
        "threshold": 1,
        "evidence": "large service-like file",
    },
    {
        "id": "unbounded-retry",
        "pack": "integration",
        "severity": "P1",
        "confidence": 0.84,
        "regex": r"(while\s*\(\s*true\s*\)|for\s*\(\s*;\s*;\s*\)|retry)",
        "missing": r"(dead.?letter|backoff|max.?retry|retry.?limit|circuit.?breaker|exhaust)",
        "threshold": 1,
        "evidence": "retry language without bounded failure policy",
    },
    {
        "id": "naive-exactly-once",
        "pack": "integration",
        "severity": "P1",
        "confidence": 0.82,
        "regex": r"\b(publish|consume|consumer|producer|queue|topic|broker|message\s*handler|event\s*handler|redeliver|ack)\b",
        "missing": r"(idempot|dedup|processed.?message|outbox|inbox)",
        "threshold": 2,
        "evidence": "message flow language without idempotency or replay terms",
    },
    {
        "id": "hidden-router",
        "pack": "integration",
        "severity": "P2",
        "confidence": 0.76,
        "regex": r"(route|destination|topic|queue|tenant)",
        "requires": r"\b(if|switch|case|elif)\b",
        "threshold": 2,
        "evidence": "routing terms mixed with branching",
    },
    {
        "id": "chatty-integration",
        "pack": "integration",
        "severity": "P2",
        "confidence": 0.67,
        "regex": r"(http\.|fetch\(|rest|grpc|client\.)",
        "threshold": 8,
        "evidence": "many remote-call terms in one surface",
    },
]


def is_generated(text: str) -> bool:
    head = text[:600].casefold()
    return any(marker in head for marker in GENERATED_PATTERNS)


def iter_scan_files(
    root: Path,
    include_docs: bool = False,
    include_generated: bool = False,
    limit: int = 1200,
) -> list[Path]:
    if root.is_file():
        return [root]
    suffixes = set(CODE_SUFFIXES)
    if include_docs:
        suffixes |= DOC_SUFFIXES
    files: list[Path] = []
    for path in root.rglob("*"):
        if any(part in SKIP_DIRS for part in path.parts):
            continue
        if not path.is_file() or path.suffix.lower() not in suffixes:
            continue
        if not include_generated:
            try:
                if is_generated(path.read_text(encoding="utf-8", errors="ignore")):
                    continue
            except OSError:
                continue
        files.append(path)
    return files[:limit]


def evidence_snippet(lines: list[str], line_number: int, radius: int = 2) -> str:
    if not lines:
        return ""
    start = max(0, line_number - radius - 1)
    end = min(len(lines), line_number + radius)
    return "\n".join(f"{index + 1}: {lines[index]}" for index in range(start, end))


def _line_for_match(text: str, match: re.Match[str] | None) -> int:
    if not match:
        return 1
    return text[: match.start()].count("\n") + 1


def scan_text(
    text: str,
    source: str = "<text>",
    pack: str = "all",
    min_confidence: float = 0.0,
) -> dict[str, Any]:
    lines = text.splitlines()
    findings = []
    for rule in RULES:
        if pack != "all" and rule["pack"] != pack:
            continue
        if float(rule["confidence"]) < min_confidence:
            continue
        matches = list(re.finditer(rule["regex"], text, re.IGNORECASE))
        if len(matches) < int(rule.get("threshold", 1)):
            continue
        if rule.get("requires") and not re.search(str(rule["requires"]), text, re.IGNORECASE):
            continue
        if rule.get("missing") and re.search(str(rule["missing"]), text, re.IGNORECASE):
            continue
        if rule.get("line_threshold") and len(lines) < int(rule["line_threshold"]):
            continue
        line_number = _line_for_match(text, matches[0] if matches else None)
        smell = find_entry(rule["id"], include_snippets=False) or {}
        findings.append(
            {
                "slug": rule["id"],
                "smell": rule["id"],
                "name": smell.get("name", rule["id"]),
                "pack": rule["pack"],
                "severity": rule["severity"],
                "confidence": rule["confidence"],
                "file": source,
                "line": line_number,
                "evidence": rule["evidence"],
                "snippet": evidence_snippet(lines, line_number),
                "patterns": smell.get("patterns", []),
                "checks": smell.get("checks", [])[:4],
            }
        )
    patterns = sorted({pattern for finding in findings for pattern in finding.get("patterns", [])})
    return {
        "path": source,
        "findings": sorted(findings, key=lambda item: (item["severity"], item["file"], item["line"], item["smell"])),
        "count": len(findings),
        "patterns": [find_entry(slug, include_snippets=False) for slug in patterns if find_entry(slug, include_snippets=False)],
        "paths": decision_paths([find_entry(finding["smell"], include_snippets=False) for finding in findings if find_entry(finding["smell"], include_snippets=False)]),
        "rulePacks": sorted({rule["pack"] for rule in RULES}),
    }


def scan_path(
    path: str | Path,
    pack: str = "all",
    include_docs: bool = False,
    include_generated: bool = False,
    min_confidence: float = 0.0,
) -> dict[str, Any]:
    root = Path(path).resolve()
    if not root.exists():
        raise FileNotFoundError(f"Scan path does not exist: {path}")
    findings = []
    base = root if root.is_dir() else root.parent
    for file_path in iter_scan_files(root, include_docs=include_docs, include_generated=include_generated):
        try:
            text = file_path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        rel = str(file_path.relative_to(base))
        result = scan_text(text, rel, pack=pack, min_confidence=min_confidence)
        findings.extend(result["findings"])
    findings.sort(key=lambda item: (item["severity"], item["file"], item["line"], item["smell"]))
    patterns = sorted({pattern for finding in findings for pattern in finding.get("patterns", [])})
    return {
        "path": str(root),
        "findings": findings,
        "count": len(findings),
        "patterns": [find_entry(slug, include_snippets=False) for slug in patterns if find_entry(slug, include_snippets=False)],
        "paths": decision_paths([find_entry(finding["smell"], include_snippets=False) for finding in findings if find_entry(finding["smell"], include_snippets=False)]),
        "rulePacks": sorted({rule["pack"] for rule in RULES}),
        "ignoredByDefault": sorted(SKIP_DIRS),
    }
